language: python
python:
  - 3.6

install:
  - pip install --upgrade pip
  - pip install -e . | grep 'Collecting\|Using cached\|Requirement already satisfied\| installed'
  - pip install -r requirements-dev.txt | grep 'Collecting\|Using cached\|Requirement already satisfied\| installed'


script:
  - black --diff geoopt
  - py.test -v
